#
# OriginPHP Framework
# Copyright 2021 Jamiel Sharief.
#
# Licensed under The MIT License
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
#
# @copyright    Copyright (c) Jamiel Sharief
# @link         https://www.originphp.com
# @license      https://opensource.org/licenses/mit-license.php MIT License
#
name: CI
on:
  push:
jobs:
  tests:
    name: "PHP ${{ matrix.php-version }} ${{ matrix.database }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        database:
          - mysql
          - postgres
          - sqlite
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
      - name: Setup MySQL
        if: matrix.database == 'mysql'
        run: docker run -d -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=chronos_test -p 3306:3306 mysql --default-authentication-plugin=mysql_native_password --disable-log-bin
      - name: Setup PostgresSQL
        if: matrix.database == 'postgres'
        run: docker run -d -e POSTGRES_PASSWORD=root -e POSTGRES_DB=chronos_test -p 5432:5432 postgres
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2
          extensions: pdo_mysql, pdo_sqlite, pdo_pgsql
      - name: Install dependencies
        run: |
          composer require php-coveralls/php-coveralls:^2.4 --dev --no-update
          composer update --no-progress --prefer-dist
      - name: Run PHPUnit
        run: |
          if [[ ${{ matrix.database }} == 'sqlite' ]]; then
            export DB_USERNAME=jim;
          fi;
          if [[ ${{ matrix.database }} == 'mysql' ]]; then
             export DB_USERNAME=root;
          fi;
          if [[ ${{ matrix.database }} == 'postgres' ]]; then
             export DB_USERNAME=postgres;
          fi;
          php vendor/bin/phpunit --coverage-clover=clover.xml
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: chronos_test
          DB_PASSWORD: root
          DB_ENGINE: ${{ matrix.database }}
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "php vendor/bin/php-coveralls --verbose"
        if: ${{ success() }}
      - name: Run PHPStan 
        run: "vendor/bin/phpstan analyse src --error-format=github"